"""Domain vocabulary: medical, sports, tourism roots.

These are domain-specific terms that a generic Turkish dictionary may not
contain but that should be recognised as valid ROOT tokens rather than
left as unknown fragments.

The domain vocabulary is an **optional support layer** — the core
segmentation engine works without it.  It is consulted during candidate
scoring to boost the score of candidates whose root matches a known
domain term.
"""

from __future__ import annotations

MEDICAL_ROOTS: dict[str, str] = {
    "glomerül": "glomerül",       "glomerülonefrit": "glomerülonefrit",
    "nefron": "nefron",           "nefropati": "nefropati",
    "hepatosit": "hepatosit",     "hepatit": "hepatit",
    "eritrosit": "eritrosit",     "lökosit": "lökosit",
    "trombosit": "trombosit",     "nötrofil": "nötrofil",
    "eozinofil": "eozinofil",     "bazofil": "bazofil",
    "lenfosit": "lenfosit",       "monosit": "monosit",
    "makrofaj": "makrofaj",       "antijen": "antijen",
    "antikor": "antikor",         "sitokin": "sitokin",
    "reseptör": "reseptör",       "ligand": "ligand",
    "enzim": "enzim",             "substrat": "substrat",
    "inhibitör": "inhibitör",     "agonist": "agonist",
    "antagonist": "antagonist",   "nöron": "nöron",
    "sinaps": "sinaps",           "akson": "akson",
    "dendrit": "dendrit",         "miyelin": "miyelin",
    "nekroz": "nekroz",           "apoptoz": "apoptoz",
    "fibrozis": "fibrozis",       "skleroz": "skleroz",
    "stenoz": "stenoz",           "embolizm": "embolizm",
    "tromboz": "tromboz",         "iskemi": "iskemi",
    "hipoksi": "hipoksi",         "asidoz": "asidoz",
    "alkaloz": "alkaloz",         "sepsis": "sepsis",
    "edema": "edema",             "enflamasyon": "enflamasyon",
    "granülom": "granülom",       "metaplazi": "metaplazi",
    "displazi": "displazi",       "neoplazi": "neoplazi",
    "karsinoma": "karsinoma",     "sarkom": "sarkom",
    "lenfoma": "lenfoma",         "lösemi": "lösemi",
    "melanom": "melanom",         "adenom": "adenom",
    "polip": "polip",             "kist": "kist",
    "abse": "abse",               "fistül": "fistül",
    "perforasyon": "perforasyon", "obstrüksiyon": "obstrüksiyon",
    "invajinasyon": "invajinasyon",
    "intususepsiyon": "intususepsiyon",
    "atelektazi": "atelektazi",   "pnömotoraks": "pnömotoraks",
    "hidrotoraks": "hidrotoraks", "plevral": "plevral",
    "bakteri": "bakteri",         "virüs": "virüs",
    "parazit": "parazit",         "mantar": "mantar",
    "protozoa": "protozoa",       "helmint": "helmint",
    "endotoksin": "endotoksin",   "ekzotoksin": "ekzotoksin",
    "antibiyotik": "antibiyotik", "antiviral": "antiviral",
    "antifungal": "antifungal",   "streptokokus": "streptokokus",
    "stafilokokus": "stafilokokus", "escherichia": "escherichia",
    "klebsiella": "klebsiella",   "pseudomonas": "pseudomonas",
    "salmonella": "salmonella",   "shigella": "shigella",
    "mycobacterium": "mycobacterium",
    "helicobacter": "helicobacter",
    "candida": "candida",         "aspergillus": "aspergillus",
    "plasmodium": "plasmodium",   "toxoplasma": "toxoplasma",
    "influenza": "influenza",     "rotavirus": "rotavirus",
    "adenovirus": "adenovirus",   "coronavirus": "coronavirus",
    "farmakokinetik": "farmakokinetik",
    "farmakodinami": "farmakodinami",
    "biyoyararlanım": "biyoyararlanım",
    "metabolit": "metabolit",     "toksisite": "toksisite",
    "plazma": "plazma",           "serum": "serum",
    "doz": "doz",
    "morfin": "morfin",           "kodein": "kodein",
    "aspirin": "aspirin",         "paracetamol": "paracetamol",
    "ibuprofen": "ibuprofen",     "warfarin": "warfarin",
    "heparin": "heparin",         "insülin": "insülin",
    "kortizol": "kortizol",       "kortikosteroid": "kortikosteroid",
    "betabloker": "betabloker",   "diüretik": "diüretik",
    "statin": "statin",           "metformin": "metformin",
    "semptom": "semptom",         "bulgu": "bulgu",
    "tanı": "tanı",               "tedavi": "tedavi",
    "prognoz": "prognoz",         "komplikasyon": "komplikasyon",
    "kontrendikasyon": "kontrendikasyon",
    "endikasyon": "endikasyon",   "biyopsi": "biyopsi",
    "aspirasyon": "aspirasyon",   "transplantasyon": "transplantasyon",
    "transplant": "transplant",   "diyaliz": "diyaliz",
    "kemoterapi": "kemoterapi",   "radyoterapi": "radyoterapi",
    "immunoterapi": "immunoterapi",
    "laparoskopi": "laparoskopi", "endoskopi": "endoskopi",
    "kolonoskopi": "kolonoskopi", "bronkoskopi": "bronkoskopi",
    "kateter": "kateter",         "stent": "stent",
    "bypass": "bypass",           "anastomoz": "anastomoz",
    "kardiyak": "kardiyak",       "pulmoner": "pulmoner",
    "hepatik": "hepatik",         "renal": "renal",
    "serebral": "serebral",       "vasküler": "vasküler",
    "endokrin": "endokrin",       "immün": "immün",
    "konjenital": "konjenital",   "herediter": "herediter",
    "otoimmün": "otoimmün",       "idiyopatik": "idiyopatik",
    "akut": "akut",               "kronik": "kronik",
    "primer": "primer",           "sekonder": "sekonder",
    "malign": "malign",           "benign": "benign",
    "solid": "solid",             "kistik": "kistik",
    "bilateral": "bilateral",     "unilateral": "unilateral",
    "sistemik": "sistemik",       "lokal": "lokal",
    "diffüz": "diffüz",           "fokal": "fokal",
    "infeksiyon": "infeksiyon",   "enfeksiyon": "enfeksiyon",
    "subakut": "subakut",         "subklinik": "subklinik",
    "progesteron": "progesteron", "prolaktin": "prolaktin",
    "prostaglandin": "prostaglandin",
    "displazi": "displazi",       "disfaji": "disfaji",
    "disfonksiyon": "disfonksiyon",
    "hemoglobin": "hemoglobin",   "hematokrit": "hematokrit",
    "kreatinin": "kreatinin",     "üre": "üre",
    "glukoz": "glukoz",           "kolesterol": "kolesterol",
    "trigliserit": "trigliserit", "albumin": "albumin",
    "bilirubin": "bilirubin",     "transaminaz": "transaminaz",
    "amilaz": "amilaz",           "lipaz": "lipaz",
    "troponin": "troponin",       "kreatinkinaz": "kreatinkinaz",
    "prokalsitonin": "prokalsitonin",
}

SPORTS_ROOTS: dict[str, str] = {
    "lig": "lig",         "kulüp": "kulüp",
    "şampiyon": "şampiyon", "turnuva": "turnuva",
    "kupa": "kupa",       "finalist": "finalist",
    "semifinal": "semifinal", "stadyum": "stadyum",
    "transfer": "transfer", "bonservis": "bonservis",
    "futbolcu": "futbolcu", "kaleci": "kaleci",
    "forvet": "forvet",   "defans": "defans",
    "offside": "offside", "penaltı": "penaltı",
    "frikik": "frikik",   "korner": "korner",
}

TOURISM_ROOTS: dict[str, str] = {
    "otel": "otel",       "hostel": "hostel",
    "resort": "resort",   "transfer": "transfer",
    "rezervasyon": "rezervasyon",
    "bagaj": "bagaj",     "terminal": "terminal",
    "destinasyon": "destinasyon",
    "tur": "tur",         "turist": "turist",
    "turizm": "turizm",   "rehber": "rehber",
    "konaklama": "konaklama", "kapasite": "kapasite",
    "sezon": "sezon",     "charter": "charter",
    "paket": "paket",     "voucher": "voucher",
    "menü": "menü",       "restoran": "restoran",
    "spa": "spa",         "havuz": "havuz",
    "suit": "suit",       "standart": "standart",
    "delüks": "delüks",
}

                                                              
ALL_DOMAIN_ROOTS: frozenset[str] = frozenset(
    k.lower()
    for d in (MEDICAL_ROOTS, SPORTS_ROOTS, TOURISM_ROOTS)
    for k in d
)
